apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-eksproject-helloworld
  namespace: argocd
  labels:
    name: argo-eksproject-helloworld
    type: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Application - hello world
  # Allow manifests to be deployed from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the dev cluster
  destinations:
    - namespace: dev
      server: https://57EAEB523E1F23421B9D5975718CB6F4.gr7.us-east-1.eks.amazonaws.com
  # Allow all cluster-scoped resources
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # Allow all namespace-scoped resources
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
