apiVersion: v1
kind: Secret
metadata:
  name: argo-repo-helloworld
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/pai12345/Andromeda_Infrastructure.git
  password: <username>
  username: <token>